### ISSUE TITLE
Newest EOS Test 3 Fails

### ISSUE THREAD

**Issue by ricktobacco** [tokenika/eosfactory#119]
After upgrading my eosio, eosio.cdt, and eosfactory I ran python3 tests/02_eosio_token.py and the followign errors surfaced when the contract was being built:

======================================================================
ERROR: test_01 (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ricardo/Documents/eosfactory/eosfactory/core/teos.py", line 130, in ABI
    process(command_line, target_dir)
  File "/home/ricardo/Documents/eosfactory/eosfactory/core/teos.py", line 430, in process
    raise errors.Error(out_err)
eosfactory.core.errors.Error: ERROR:
In file included from /home/ricardo/Documents/contracts/_iqhgcqllgnpkirjwwkms/src/_iqhgcqllgnpkirjwwkms.cpp:8:
In file included from /home/ricardo/Documents/contracts/_iqhgcqllgnpkirjwwkms/src/_iqhgcqllgnpkirjwwkms.hpp:7:
In file included from /usr/opt/eosio.cdt/1.5.0-rc2/bin/../include/eosiolib/asset.hpp:3:
/usr/opt/eosio.cdt/1.5.0-rc2/bin/../include/eosiolib/print.hpp:248:7: error: call to 'print' is ambiguous
      print(std::forward<Arg>(a));

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/02_eosio_token.py", line 42, in test_01
    contract.build()
  File "/home/ricardo/Documents/eosfactory/eosfactory/shell/contract.py", line 54, in build
    self.build_abi()
  File "/home/ricardo/Documents/eosfactory/eosfactory/shell/contract.py", line 48, in build_abi
    teos.ABI(self.contract_dir)
  File "/home/ricardo/Documents/eosfactory/eosfactory/core/teos.py", line 132, in ABI
    raise errors.Error(str(e))
eosfactory.core.errors.Error: ERRO

**Comment by jakub-zarembinski** [comment]
Did you close the issue because the problem had disappeared?
