### ISSUE TITLE
Unable to build any contract

### ISSUE THREAD

**Issue by batrlatom** [tokenika/eosfactory#126]
I installed eos factory into miniconda environment with python3.6 by using
pip install eosfactory . Creating accounts, reseting node works fine, but  I am unable
to deploy any contract. Can you help me out?

Using contract from template:
It freezes during the compilation

Using my own contract:
File "/home/recall/miniconda3/envs/recall/lib/python3.6/site-packages/eosfactory/core/teos.py", line 130, in ABI
    process(command_line, target_dir)
  File "/home/recall/miniconda3/envs/recall/lib/python3.6/site-packages/eosfactory/core/teos.py", line 418, in process
    os.mkdir(cwd)
FileExistsError: [Errno 17] File exists: '/home/recall/eostest/contracts/hello/../build/cwd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/recall/miniconda3/envs/recall/lib/python3.6/site-packages/eosfactory/shell/contract.py", line 48, in build_abi
    teos.ABI(self.contract_dir)
  File "/home/recall/miniconda3/envs/recall/lib/python3.6/site-packages/eosfactory/core/teos.py", line 132, in ABI
    raise errors.Error(str(e))

**Comment by stefanzarembinski** [comment]
Will you, please, install EOSFactory with its 'install.sh' inataller?
The 'pip' installer is not ready yet.

**Comment by batrlatom** [comment]
Hi, thanks for reply. I did the clean install with 'install.sh'. But he problem at the end was not with eos factory, but was related to the number of cores for eos-cpp . Now with more than 1 cores and it works just fine. Thanks
