### ISSUE TITLE
Running on Xubuntu 18 (Xenial) gives /bin/sh: 1: gnome-terminal: not found

### ISSUE THREAD

**Issue by mtsalenc** [tokenika/eosfactory#29]
This is very likely a distro-related question. Running `node.reset()` on the python CLI after building and sourcing the environment variables gives:
```
/bin/sh: 1: gnome-terminal: not found
False
```
Runnig tests fails too:

```
$ python3 ./tests/unittest1.py 
/bin/sh: 1: gnome-terminal: not found
ERROR!
connect: Connection refused

E
======================================================================
ERROR: setUpClass (__main__.Test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/unittest1.py", line 26, in setUpClass
    sess.init()
  File "/home/rigel/Apps/eosfactory/pyteos/sess.py", line 41, in init
    wallet = pyteos.Wallet()
  File "/home/rigel/Apps/eosfactory/pyteos/pyteos.py", line 771, in __init__
    self.json["keys"] = []
TypeError: 'str' object does not support item assignment

----------------------------------------------------------------------
Ran 0 tests in 15.579s

FAILED (errors=1)
```

Also relevant:
When running
> ./build.sh -e /path/to/your/local/EOSIO/repository -w /path/to/your/local/workspace

from the instructions, my command looked like this:
> ./build.sh -e ~/eos -w ~/workspace

where `~/eos` is eosio dawn-v4.0.0 directory and `~/workspace` is an empty directory

**Comment by mtsalenc** [comment]
Thought having `/bin/sh` linked to `/bin/bash` would be enough but no.
Fixed by installing gnome terminal

`sudo apt install gnome-terminal`

Thanks to user trungtt1981 :100:
