### ISSUE TITLE
unittest1-3 fails

### ISSUE THREAD

**Issue by jonericcook** [tokenika/eosfactory#36]
Jon-Erics-MacBook-Pro:eosfactory joneric.cook$ python3 ./tests/unittest1.py 
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py:839: ResourceWarning: subprocess 727 is still running
  ResourceWarning, source=self)
E
======================================================================
ERROR: setUpClass (__main__.Test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/unittest1.py", line 24, in setUpClass
    assert(not testnet.error)
AssertionError

----------------------------------------------------------------------
Ran 0 tests in 15.402s

FAILED (errors=1)
Jon-Erics-MacBook-Pro:eosfactory joneric.cook$ python3 ./tests/unittest2.py 
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py:839: ResourceWarning: subprocess 752 is still running
  ResourceWarning, source=self)
E
======================================================================
ERROR: setUpClass (__main__.Test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/unittest2.py", line 23, in setUpClass
    assert(not testnet.error)
AssertionError

----------------------------------------------------------------------
Ran 0 tests in 16.365s

FAILED (errors=1)
Jon-Erics-MacBook-Pro:eosfactory joneric.cook$ python3 ./tests/unittest3.py 
##### verbose mode is set!
#       nodeos exe file: /usr/local/bin/nodeos
#    genesis state file: /Users/joneric.cook/eosfactory/build/daemon/data-dir/genesis.json
#        server address: 127.0.0.1:8888
#      config directory: /Users/joneric.cook/eosfactory/build/daemon/data-dir/
#      wallet directory: /Users/joneric.cook/eosfactory/build/daemon/data-dir/wallet/

/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py:839: ResourceWarning: subprocess 778 is still running
  ResourceWarning, source=self)
E
======================================================================
ERROR: setUpClass (__main__.Test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/unittest3.py", line 26, in setUpClass
    assert(not testnet.error)
AssertionError

----------------------------------------------------------------------
Ran 0 tests in 16.371s

FAILED (errors=1)

Oddly enough, node.reset(), node.stop(), node.info(), node.run() all work fine.

**Comment by andresberrios** [comment]
I'm getting the same errors when running the tests.

**Comment by basarrcan** [comment]
In my practices with eosfactory, I realized that it actually doesn't work well with v1.1, so what I'm doing is building a v1.0.8 version of eos, then make the installation of eosfactory with that version. Works fine. Assuming that there will be no difference on the contract-unittest level of code on eosio between release updates, it seems to me a viable solution until necessary fixes come for the latest branch.

**Comment by d5panchuk** [comment]
Same issue (with eos v1.3)
sess.init() fails with the same error messages as @andresberrios mentioned before
Please fix this
