### ISSUE TITLE
project_from_template fails mysteriously if directory already exists. 

### ISSUE THREAD

**Issue by noisy** [tokenika/eosfactory#56]
After running **twice** script:

```
from eosf import *
project_from_template("foo_bar", template="01_hello_world")
```

For the second time, user gets:

```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    project_from_template("foo_bar", template="01_hello_world")
  File "/home/noisy/Devel/EOS/factory/pyteos/efcon.py", line 35, in project_from_template
    '''.format(result.contract_path_absolute))
AttributeError: 'TemplateCreate' object has no attribute 'contract_path_absolute'
```

**Expected behavior**: 

User should be informed that he need to chose different name, or have a possibility to override a directory

**Comment by noisy** [comment]
This seems to be fixed on dev branch:
![selection_999 159](https://user-images.githubusercontent.com/201263/45823099-36f38480-bced-11e8-87b5-9a712ad96032.png)
