### ISSUE TITLE
Test fails when there is no prior build

### ISSUE THREAD

**Issue by jakub-zarembinski** [tokenika/eosfactory#62]
```
python3 contracts/01_hello_world/tests/unittest1.py
```

```
======================================================================
ERROR: setUpClass (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/unittest1.py", line 60, in setUpClass
    contract.build(force=False)
  File "/mnt/d/Workspaces/EOS/eosfactory/pyteos/shell/contract.py", line 77, in build
    if force or not self.is_built():
  File "/mnt/d/Workspaces/EOS/eosfactory/pyteos/shell/contract.py", line 83, in is_built
    self.contract_dir, self.wasm_file, self.abi_file)
  File "/mnt/d/Workspaces/EOS/eosfactory/pyteos/core/cleos.py", line 883, in contract_is_built
    wasm_file = config.get_wasm_file(contract_dir)
  File "/mnt/d/Workspaces/EOS/eosfactory/pyteos/core/config.py", line 556, in get_wasm_file
    getContractFile(contract_dir, ".wasm"), contract_dir)
  File "/mnt/d/Workspaces/EOS/eosfactory/pyteos/core/config.py", line 360, in getContractFile
    '''.format(contract_dir_hint, contract_file_hint, trace))
core.errors.Error: ERROR:
Cannot determine the contract file basing on hints:
        contract dir hint: /mnt/d/Workspaces/EOS/contracts/foo_bar_london/tests/../
        contract file hint: .wasm
        Tried path list:
        .wasm
/mnt/d/Workspaces/EOS/contracts/foo_bar_london/tests/../.wasm
/mnt/d/Workspaces/EOS/contracts/foo_bar_london/tests/../build/.wasm
/mnt/d/Workspaces/EOS/contracts/foo_bar_london/tests/../build

----------------------------------------------------------------------
```

**Comment by jakub-zarembinski** [comment]
Fixed in https://github.com/tokenika/eosfactory/commit/5b2b8daa4580278d77a9dd4174c0dd5518e8488a
