### ISSUE TITLE
ERROR: unexpected argument

### ISSUE THREAD

**Issue by RegulusBit** [tokenika/eosfactory#63]
Hi 
i've installed eosfactory and basic tasks like starting new chain or creating wallet and accounts works like charm, but if i want to deploy contract an error shows up. same goes for original test cases: 

user@user:~/Development/EOS/eosfactory$ python3 tests/01_hello_world.py 
```

###  SCENARIO:
Create a contract from template, then build and deploy it.

Removing testnet cache for prefix `_127_0_0_1_8888_`
Testnet cache successfully removed.
Local node is stopped [13547].
/usr/lib/python3.6/subprocess.py:766: ResourceWarning: subprocess 15170 is still running
  ResourceWarning, source=self)
....
Local node is running. Block number is 8
* Wallet name is ``_127_0_0_1_8888_default``, wallet directory is
    /home/user/eosio-wallet/.
* Created wallet ``_127_0_0_1_8888_default``.
* Password is saved to the file ``_127_0_0_1_8888_passwords.json`` in the wallet directory.
* The wallet is empty.
######### Create a master account object ``master``.
* Importing keys of the account ``eosio`` into the wallet ``_127_0_0_1_8888_default``
* Cross-checked: all account keys are in the wallet.
* Account object ``master`` stored in the file 
    ``_127_0_0_1_8888_accounts.json`` in the wallet directory:
    /home/user/eosio-wallet/_127_0_0_1_8888_accounts.json

###  setUpClass:
Create test accounts:

######### Create an account object ``alice``.
... for a new blockchain account ``3ep55o55lnk4``.
* The account object is created.
* Cross-checked: account object ``alice`` mapped to an existing account ``3ep55o55lnk4``.
* Importing keys of the account ``3ep55o55lnk4`` into the wallet ``_127_0_0_1_8888_default``
* Cross-checked: all account keys are in the wallet.
* Account object ``alice`` stored in the file 
    ``_127_0_0_1_8888_accounts.json`` in the wallet directory:
    /home/user/eosio-wallet/_127_0_0_1_8888_accounts.json
######### Create an account object ``carol``.
... for a new blockchain account ``w3qtafvzd1ht``.
* The account object is created.
* Cross-checked: account object ``carol`` mapped to an existing account ``w3qtafvzd1ht``.
* Importing keys of the account ``w3qtafvzd1ht`` into the wallet ``_127_0_0_1_8888_default``
* Cross-checked: all account keys are in the wallet.
* Account object ``carol`` stored in the file 
    ``_127_0_0_1_8888_accounts.json`` in the wallet directory:
    /home/user/eosio-wallet/_127_0_0_1_8888_accounts.json
######### Create an account object ``bob``.
... for a new blockchain account ``rud3xd5k3oe4``.
* The account object is created.
* Cross-checked: account object ``bob`` mapped to an existing account ``rud3xd5k3oe4``.
* Importing keys of the account ``rud3xd5k3oe4`` into the wallet ``_127_0_0_1_8888_default``
* Cross-checked: all account keys are in the wallet.
* Account object ``bob`` stored in the file 
    ``_127_0_0_1_8888_accounts.json`` in the wallet directory:
    /home/user/eosio-wallet/_127_0_0_1_8888_accounts.json

###  test_01:
Create, build and deploy the contract:

######### Create an account object ``host``.
... for a new blockchain account ``exkuq1lwlxh4``.
* The account object is created.
* Cross-checked: account object ``host`` mapped to an existing account ``exkuq1lwlxh4``.
* Importing keys of the account ``exkuq1lwlxh4`` into the wallet ``_127_0_0_1_8888_default``
* Cross-checked: all account keys are in the wallet.
* Account object ``host`` stored in the file 
    ``_127_0_0_1_8888_accounts.json`` in the wallet directory:
    /home/user/eosio-wallet/_127_0_0_1_8888_accounts.json
######### Create contract ``_wslqwjvacdyugodewiyd`` from template ``01_hello_world``.
Contract project '_wslqwjvacdyugodewiyd' created from template '01_hello_world' in directory
    /home/user/Development/EOS/contracts/_wslqwjvacdyugodewiyd
* Contract directory is
    /home/user/Development/EOS/contracts/_wslqwjvacdyugodewiyd
######### Create a ``Contract`` object.
* Contract directory is
    /home/user/Development/EOS/contracts/_wslqwjvacdyugodewiyd
ABI file writen to file: /home/user/Development/EOS/contracts/_wslqwjvacdyugodewiyd/build
WAST file writen to file: /home/user/Development/EOS/contracts/_wslqwjvacdyugodewiyd/build/_wslqwjvacdyugodewiyd.wast
ELocal node is stopped [15170].

======================================================================
ERROR: test_01 (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/Development/EOS/eosfactory/pyteos/core/teos.py", line 248, in WAST
    process(command_line)
  File "/home/user/Development/EOS/eosfactory/pyteos/core/teos.py", line 409, in process
    raise errors.Error(out_err)
core.errors.Error: ERROR:
unexpected argument '/home/user/Development/EOS/contracts/_wslqwjvacdyugodewiyd/build/_wslqwjvacdyugodewiyd.wasm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/01_hello_world.py", line 42, in test_01
    contract.build()
  File "/home/user/Development/EOS/eosfactory/pyteos/shell/contract.py", line 79, in build
    self.build_wast()
  File "/home/user/Development/EOS/eosfactory/pyteos/shell/contract.py", line 71, in build_wast
    teos.WAST(self.contract_dir)
  File "/home/user/Development/EOS/eosfactory/pyteos/core/teos.py", line 255, in WAST
    raise errors.Error(str(e))
core.errors.Error: ERROR:
ERROR:
unexpected argument '/home/user/Development/EOS/contracts/_wslqwjvacdyugodewiyd/build/_wslqwjvacdyugodewiyd.wasm'

----------------------------------------------------------------------
Ran 1 test in 8.234s

FAILED (errors=1)
```
am i missing something or there is a bug in process? 

thanks for this awesome tool :+1:

**Comment by RegulusBit** [comment]
is there any updates on this issue?

**Comment by noisy** [comment]
@RegulusBit  We just released new version of EOS Factory (https://github.com/tokenika/eosfactory/releases)

Could you confirm whether this still is a problem?
