### ISSUE TITLE
Test 03 for `KYLIN -r` fails in branch `dev`

### ISSUE THREAD

**Issue by jakub-zarembinski** [tokenika/eosfactory#64]
```
$ python3 tests/03_tic_tac_toe.py KYLIN -r
```
```
######### Create a master account object ``master``.
E
======================================================================
ERROR: setUpClass (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/03_tic_tac_toe.py", line 48, in setUpClass
    create_master_account("master", testnet)
  File "/mnt/d/Workspaces/EOS/eosfactory/pyteos/shell/account.py", line 454, in create_master_account
    account_object_name, account_name, owner_key, active_key, verbosity)
  File "/mnt/d/Workspaces/EOS/eosfactory/pyteos/shell/account.py", line 224, in __init__
    self.has_keys = owner_key and not owner_key.key_private is None
AttributeError: 'str' object has no attribute 'key_private'

----------------------------------------------------------------------
```

**Comment by jakub-zarembinski** [comment]
Fixed
