### ISSUE TITLE
NameError: name 'trace' is not defined

### ISSUE THREAD

**Issue by noisy** [tokenika/eosfactory#66]
- branch: master (41b20835df61a30177e7baa2e6ffeb141a7775c0)

After running: `python tests/01_hello_world.py`

error is returned:

```
mesg: ttyname failed: Inappropriate ioctl for device
E
======================================================================
ERROR: setUpClass (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/01_hello_world.py", line 19, in setUpClass
    reset()
  File "/opt/eosfactory/pyteos/core/manager.py", line 105, in reset
    if not cleos.set_local_nodeos_address_if_none():
  File "/opt/eosfactory/pyteos/core/cleos.py", line 18, in set_local_nodeos_address_if_none
    "http://" + config.getHttpServerAddress())
  File "/opt/eosfactory/pyteos/core/config.py", line 371, in getHttpServerAddress
    return configValue("EOSIO_DAEMON_ADDRESS")
  File "/opt/eosfactory/pyteos/core/config.py", line 107, in configValue
    retval = configValues(config_key)
  File "/opt/eosfactory/pyteos/core/config.py", line 87, in configValues
    config_json = config_map()
  File "/opt/eosfactory/pyteos/core/config.py", line 74, in config_map
    path = config_file()
  File "/opt/eosfactory/pyteos/core/config.py", line 69, in config_file
    logger.INFO('''Creating an empty config file: {}'''.format(file, trace))
NameError: name 'trace' is not defined

----------------------------------------------------------------------
Ran 0 tests in 0.008s

FAILED (errors=1)
```

**Comment by noisy** [comment]
It looks like this was introduced in https://github.com/tokenika/eosfactory/commit/41b20835df61a30177e7baa2e6ffeb141a7775c0#diff-69c26570ab23d8ef51ca1028810fad70L91

**Comment by stefanzarembinski** [comment]
Fixed
