### ISSUE TITLE
'utf-8' codec can't decode byte 0xd8 in position 5030: invalid continuationbyte

### ISSUE THREAD

**Issue by mintzhao** [tokenika/eosfactory#95]
### error output
```
Traceback (most recent call last):
  File "./tests/test1.py", line 145, in <module>
    test()
  File "./tests/test1.py", line 127, in test
    b)
  File "/Users/mint/Documents/eosfactory/eosfactory/shell/account.py", line 583, in push_action
    is_verbose=False, json=True)
  File "/Users/mint/Documents/eosfactory/eosfactory/core/cleos.py", line 1002, in __init__
    _Cleos.__init__(self, args, "push", "action", is_verbose)
  File "/Users/mint/Documents/eosfactory/eosfactory/core/cleos.py", line 59, in __init__
    self.out_msg = process.stdout.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 5030: invalid continuationbyte
The terminal process terminated with exit code: 1
```

when I change cleos.py to
```
# self.out_msg = process.stdout.decode("utf-8")
self.out_msg = process.stdout.decode("ISO-8859-1")
# self.out_msg_details = process.stderr.decode("utf-8")
self.out_msg_details = process.stderr.decode("ISO-8859-1")
```
it's ok, no error occurs

**Comment by stefanzarembinski** [comment]
Thank you, we take your advice.

SZ
